<div>
    <x-modal wire:model="show" title="Example Modal">
        {{ $text }}

        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at. Donec enim diam vulputate ut pharetra sit amet. Congue mauris rhoncus aenean vel elit. Adipiscing vitae proin sagittis nisl. Sit amet mattis vulputate enim nulla aliquet porttitor. Faucibus vitae aliquet nec ullamcorper sit. Enim tortor at auctor urna nunc id cursus metus aliquam. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Enim eu turpis egestas pretium. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Non quam lacus suspendisse faucibus interdum. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Cursus in hac habitasse platea dictumst quisque. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed. Elementum nisi quis eleifend quam adipiscing vitae. Aliquam nulla facilisi cras fermentum odio eu. Donec pretium vulputate sapien nec sagittis.

        Arcu non sodales neque sodales. Viverra orci sagittis eu volutpat odio facilisis mauris. Ac ut consequat semper viverra nam libero justo laoreet. Interdum velit laoreet id donec ultrices tincidunt arcu. Egestas tellus rutrum tellus pellentesque eu tincidunt. Dui sapien eget mi proin sed libero. Rhoncus mattis rhoncus urna neque viverra. Turpis tincidunt id aliquet risus feugiat. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Sem viverra aliquet eget sit amet tellus. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Id diam vel quam elementum pulvinar etiam non. Urna nunc id cursus metus aliquam eleifend. At elementum eu facilisis sed odio morbi quis commodo. Arcu cursus euismod quis viverra nibh cras pulvinar. Eu mi bibendum neque egestas congue quisque egestas. Id donec ultrices tincidunt arcu non sodales. Imperdiet nulla malesuada pellentesque elit eget gravida cum.

        Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Lectus urna duis convallis convallis tellus id interdum velit. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Id velit ut tortor pretium viverra suspendisse potenti nullam. Imperdiet sed euismod nisi porta lorem mollis aliquam. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Vitae turpis massa sed elementum tempus egestas sed sed risus. Et egestas quis ipsum suspendisse. Id semper risus in hendrerit. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Ultricies mi quis hendrerit dolor magna eget est lorem ipsum. Fermentum iaculis eu non diam. Proin sed libero enim sed faucibus. Molestie a iaculis at erat. At in tellus integer feugiat scelerisque varius morbi enim nunc. Tellus integer feugiat scelerisque varius morbi enim nunc.

        Donec adipiscing tristique risus nec feugiat in fermentum. Lectus vestibulum mattis ullamcorper velit sed. Proin libero nunc consequat interdum varius. Pellentesque habitant morbi tristique senectus et. Eu sem integer vitae justo eget magna fermentum iaculis. Etiam non quam lacus suspendisse. Interdum velit laoreet id donec ultrices tincidunt arcu. In ornare quam viverra orci sagittis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Sapien nec sagittis aliquam malesuada bibendum arcu. Id eu nisl nunc mi ipsum. Felis bibendum ut tristique et egestas. Nunc sed id semper risus in hendrerit gravida rutrum. Vitae congue eu consequat ac felis.

        Elit at imperdiet dui accumsan sit amet. Consequat ac felis donec et odio pellentesque diam. Felis eget velit aliquet sagittis id. Vehicula ipsum a arcu cursus vitae congue mauris. Placerat in egestas erat imperdiet sed euismod nisi porta. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Urna nunc id cursus metus aliquam eleifend mi. Ac felis donec et odio pellentesque diam volutpat. Odio facilisis mauris sit amet massa vitae tortor. Lobortis scelerisque fermentum dui faucibus in ornare. Ultrices gravida dictum fusce ut placerat. Tellus elementum sagittis vitae et leo duis ut. Dictum at tempor commodo ullamcorper a lacus vestibulum. Vulputate enim nulla aliquet porttitor lacus luctus. Fermentum et sollicitudin ac orci phasellus. Egestas pretium aenean pharetra magna ac. Purus gravida quis blandit turpis cursus in. Suspendisse in est ante in nibh mauris cursus mattis molestie.

        @section('buttons')
            <x-buttons.secondary-base @click="show=false">Close</x-buttons.secondary-base>
        @endsection
    </x-modal>
</div>
